name: "Herb"

networks:
    # for creating & maintianing
    # the searchable web database
    infrastructure:

    # for handling the reception and
    # evaluation of, and response to,
    # user search queries
    userspace:

services:
    db:
        networks:
            - infrastructure
            - userspace
        image: postgres:18.4-alpine
        container_name: herb-db
        environment:
            PGUSER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PORT: ${DB_CONTAINER_PORT}
        volumes:
            - db-data:/var/lib/herb
        healthcheck:
            # Command for live tracking:
            # watch -n 1 'psql -d herb -c "SELECT count(*) AS link_queue_count FROM link_queue; SELECT count(*) AS pages_count FROM pages; SELECT count(*) AS sites_count FROM sites;"'
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

    # backup:
    #     image: postgres:18.4-alpine
    #     container_name: herb-db-backup

    crawler:
        networks:
            - infrastructure
        build:
            context: ./services/crawler
            dockerfile: ./build/dockerfile
        container_name: herb-crawler
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - ./.env

    indexer:
        networks:
            - infrastructure
        build:
            context: ./services/indexer
            dockerfile: ./dockerfile
        container_name: herb-indexer
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - ./.env

    ranking_engine:
        networks:
            - infrastructure
        build:
            context: ./services/ranking_engine
            dockerfile: ./dockerfile
        container_name: herb-ranking_engine
        depends_on:
            db:
                condition: service_healthy

    query_engine:
        networks:
            - "userspace"
        build:
            context: ./services/query_engine
            dockerfile: ./dockerfile
        container_name: herb-query_engine
        depends_on:
            db:
                condition: service_healthy

    client:
        networks:
            - userspace
        build:
            context: ./services/client
            dockerfile: ./dockerfile
        container_name: herb-client
        depends_on:
            db:
                condition: service_healthy

    server:
        container_name: herb-server
        image: nginx:stable-alpine-slim
        networks:
            - userspace
        volumes:
            - ./services/server/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./services/client:/var/www/html:ro
        ports:
            - "3020:80"

volumes:
    db-data:
