name: "Herb"

services:
    db:
        image: postgres:18.4-alpine
        container_name: herb-db
        environment:
            PGUSER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PORT:
        volumes:
            - db-data:/var/lib/herb
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "3020:5432"

    # backup:
    #     image: postgres:18.4-alpine
    #     container_name: herb-db-backup

    crawler:
        build:
            context: ./crawler
        container_name: herb-crawler
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - ./.env
        ports:
            - "3021:3001"

    client:
        image: amazoncorretto:26-alpine # OpenJDK distribution maintained by AWS
        depends_on:
            db:
                condition: service_healthy

volumes:
    db-data:
