-- +goose Up
ALTER TABLE pages
ADD COLUMN date_discovered TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE pages
ADD COLUMN date_last_crawled TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sites
ADD COLUMN date_discovered TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE sites
ADD COLUMN date_last_crawled TIMESTAMP DEFAULT CURRENT_TIMESTAMP;