FROM python:3 AS builder

WORKDIR /app

COPY . .

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"

RUN pip install -r requirements.txt

FROM python:3-alpine

WORKDIR /app

COPY --from=builder /venv /venv
ENV PATH="/venv/bin:$PATH"

COPY . .

EXPOSE 3000

CMD ["/venv/bin/python3", "main.py"]